### PR TITLE
Added New Store Link for PlebNet Dev Merchandise 

### PR DESCRIPTION
**Pull request by Bitc0indad**
Footer and Header buttons for Store added. Deployed on Vercel for review: https://website-bitc0indad.vercel.app/

@eriknewland  there is also a commit for the duplicated blog post we discussed, it was still lingering in my git status as well. Please reach out if you have any questions etc. 

Footer and Header for Store added.

### CODE REVIEW

**Comment by eriknewland** [comment]
I think the store link should open up in a new tab/window (see the HTML attribute target=_blank)

**Comment by bitkarrot** [comment]
agreed with @eriknewland

**Comment by Bitc0indad** [comment]
We're using Astro component (which file) to render the navigation links right? I think we need to ensure that it supports the target attribute and properly applies it to the resulting HTML. At deadstop with data.js updated as recommended but not showing up when deployed.

**Comment by eriknewland** [comment]
> We're using Astro component (which file) to render the navigation links right? I think we need to ensure that it supports the target attribute and properly applies it to the resulting HTML. At deadstop with data.js updated as recommended but not showing up when deployed.

the issue is that the the template file for the header (src/components/widgets/Header.astro) doesn't contain a reference to the 'target' property you're creating in data.js. We could either adjust the template accordingly, or we can just add a little conditional logic to have only our 'Store' link open in a new page.

Remove 'target' from data.js, and adjust `src/components/widgets/Header.astro` accordingly:

old
```javascript
                       <a
                          class="first:rounded-t last:rounded-b md:hover:bg-gray-200 dark:hover:bg-gray-700 py-2 px-5 block whitespace-no-wrap"
                          href={href2}
                        >
                          {text2}
                       </a>
```

new

```
<a
  class="first:rounded-t last:rounded-b md:hover:bg-gray-200 dark:hover:bg-gray-700 py-2 px-5 block whitespace-no-wrap"
  href={href2}
  target={text2 === 'Store' ? "_blank" : "_self"}
>
  {text2}
</a>
```

**Comment by Bitc0indad** [comment]
Updated ready for review.

**Comment by eriknewland** [comment]
Looks great! Merging

**Pull request merged**
