### PR TITLE
update all deps. to latest, Astro major version bump 3.3.3

### PR DESCRIPTION
**Pull request by bliotti**
dependencies were outdated and without a lock file. 

decided to bump all packages to the latest version.  `$ npm install -g npm-check-updates` 

$ ncu

image

astro had breaking changes.  PR has many file changes. (https://docs.astro.build/en/guides/upgrade-to/v3/)

looks to be working for me now, building and running dev.

let me know if you have questions. 

also node -v is now 18

@bitkarrot @saucy-tech

### CODE REVIEW

**Comment by bliotti** [comment]
probably should do this PR first, then #71 to lock the new state of depends down.

**Comment by bitkarrot** [comment]
> probably should do this PR first, then #71 to lock the new state of depends down.

OK sounds good. I will take a look in the AM

**Comment by bitkarrot** [comment]
Since the setup changed a bit since astro 2.0, had to do "npm install  astro" in addition to the above "npm" command: 

Ran your branch locally, 

Got some errors when visiting the /blog page

Screenshot 2023-10-25 at 11 17 19 PM

**Comment by bitkarrot** [comment]
src/pages/api/get-paylink.js 

[astro] Lower case endpoint names are deprecated and will not be supported in Astro 4.0. Rename the endpoint post to POST.

**Comment by bliotti** [comment]
[same](https://github.com/plebnet-dev/website/pull/72#issuecomment-1780495463) looks like it needs a `width and height` passed now. Will check it out

**Comment by bliotti** [comment]
> Since the setup changed a bit since astro 2.0, had to do "npm install astro" in addition to the above "npm" command:
> 
> Ran your branch locally, i'm on node v18.16.1 Got some errors when visiting the /blog page
> 
> Screenshot 2023-10-25 at 11 17 19 PM

@bitkarrot  [93db883](https://github.com/plebnet-dev/website/pull/72/commits/93db8839cf4142f4f1f9fc9ca342f2576a96d647) fixes above

**Comment by bliotti** [comment]
[93db883](https://github.com/plebnet-dev/website/pull/72/commits/93db8839cf4142f4f1f9fc9ca342f2576a96d647) 

Wasn't able to figure out how to keep images for a collection in public dir. 
This version wanted image paths for .md files to be relative. ex. `image:  ../../assets/images/code_image.jpg` (not sure if I like this)
Also [docs]( https://docs.astro.build/en/guides/images/#where-to-store-images) recommend moving images to src when possible.

**Comment by bitkarrot** [comment]
Based on the vercel performance for loading images, it's always been a little slow when they are located in `public`, as per docs, we should move them to `src` if that is the suggestion to help with the processing. 

Yes I agree the links don't look pretty but if it improves especially load time on mobile, I'd vote for moving the public images to src.

**Comment by bitkarrot** [comment]
If we move the images from `public` to `src` , the .well-known directory should stay in the `public` for nostr NIP-5 and lightning lnurlp usage

**Comment by bliotti** [comment]
@surfersol, or anyone else too, If you want, try pulling down this PR branch down to your local machine, and see if you can get it running too. `npm run dev`

- Note, the required version of node changed.
- you may need to delete the node_modules directory, to start fresh. Then run "npm install"

**Comment by bliotti** [comment]
[24aca60](https://github.com/plebnet-dev/website/pull/72/commits/24aca60ac562c8f897539b925e54caf106fa3f48) - now uses absolute image paths, no more `../..`, and collection images are moved to sep. dir. within `content` 

ref: [Astro website's repo](https://github.com/withastro/astro.build/blob/main/README.md#updating-the-showcase)

**Comment by bliotti** [comment]
> [24aca60](https://github.com/plebnet-dev/website/pull/72/commits/24aca60ac562c8f897539b925e54caf106fa3f48) - now uses absolute image paths, no more `../..`, and collection images are moved to sep. dir. within `content`
> 
> ref: [Astro website's repo](https://github.com/withastro/astro.build/blob/main/README.md#updating-the-showcase)

@bitkarrot wanna give [24aca60](https://github.com/plebnet-dev/website/pull/72/commits/24aca60ac562c8f897539b925e54caf106fa3f48) a run.

**Comment by bliotti** [comment]
Will let you know when ready for review. just noticed something with dep.

**Comment by bitkarrot** [comment]
OK, writing this into the README at top 

Use Node version - lts/hydrogen -> v18.16.1
```
$ npm install astro
$ npm install

```

**Comment by bitkarrot** [comment]
@bliotti @saucy-tech,@BrutusBondBTC  Please take note of README.md update for future builds

@BrutusBondBTC , be sure to pull down from latest to update your install

**Comment by BrutusBondBTC** [comment]
" be sure to pull down from latest to update your install"


I'm not sure I know how. 

Does this mean I type ⋮
git clone https://theURL.com

and update node.js?

**Comment by bitkarrot** [comment]
> " be sure to pull down from latest to update your install"
> 
> I'm not sure I know how.
> 
> Does this mean I type ⋮ git clone https://theURL.com
> 
> and update node.js?

reach out to me or @bliotti on the discord

**Pull request merged**
