### PR TITLE
Commit package-lock file

### PR DESCRIPTION
**Pull request by saucy-tech**
Issue #70 . Ran npm install stable@latest and npm install @astrojs/image@latest to update package.json. Removed package-lock file from git-ignore.

### CODE REVIEW

**Comment by bliotti** [comment]
Nice will test it here in a bit.

**Comment by bitkarrot** [comment]
@saucy-tech greenlight to move forward with this PR. Thanks!

**Comment by saucy-tech** [comment]
issue #70 
successful vercel build
https://plebnetdev-web-saucytech.vercel.app/

**Comment by bitkarrot** [comment]
Merged. LFG!

**Pull request merged**
