### PR TITLE
Refactor Registration form

### PR DESCRIPTION
**Pull request by amsalmeron**
In progress: LNBits iframe not copying invoice address to clipboard. 

Requires LNBits API Key

https://plebdev-website-git-registration-amsalmeron.vercel.app/Indiv

### CODE REVIEW

**Comment by bitkarrot** [comment]
@amsalmeron maybe I did not communicate this correctly, but the BOLT 11 can be done on the following page after they click on Submit, if the modal is giving you problems. having an embed might not show up too well on the page. I haven't dived into the code, but this just my observation from the vercel deploy

**Comment by bitkarrot** [comment]
Also be sure to consider mobile usage and how it displays on mobile.

**Comment by amsalmeron** [comment]
MVP is created.

Lightning invoice is created on load of form, and user is routed to sats pay invoice link upon submit. Let me how y'all feel about the workflow. Should be able to include the invoice directly on page / modal, and make get request on invoice to ensure payment is complete. 

https://plebdev-website-e67x62ndb-amsalmeron.vercel.app/

**Comment by bitkarrot** [comment]
@amsalmeron Link works, although you can just submit the form without any validation e.g. * Fields should be validated

Otherwise, link works. Either BOLT11 on page embedded, similar to https://plebnet.dev/donate page or on modal should be fine, as long as it looks good on mobile.

**Comment by bitkarrot** [comment]
@bliotti if you get a chance - please see this

**Comment by bitkarrot** [comment]
@amsalmeron we took a look, I'm having @bliotti rework this PR so that we can move to production asap.

**Comment by bitkarrot** [comment]
@amsalmeron @bliotti How's this PR coming along?

**Pull request closed without merging**
